#if TARGET_OS_SIMULATOR

#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Darwin;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PaymentSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC10PaymentSDK24AlertControllerWithBlock")
@interface AlertControllerWithBlock : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSHTTPURLResponse;
@class NSData;
@class NSError;
@class NSURLConnection;
@class NSURLAuthenticationChallenge;
@class NSURLResponse;

SWIFT_CLASS("_TtC10PaymentSDK20PGConnectionDelegate")
@interface PGConnectionDelegate : NSObject <NSURLConnectionDataDelegate>
@property (nonatomic) BOOL ignoreServerTrust;
@property (nonatomic, strong) NSHTTPURLResponse * _Null_unspecified response;
@property (nonatomic, strong) NSData * _Null_unspecified data;
@property (nonatomic, strong) NSError * _Null_unspecified error;
@property (nonatomic, strong) NSURLConnection * _Null_unspecified connection;
@property (nonatomic, copy) void (^ _Nullable completionHandler)(PGConnectionDelegate * _Nonnull);
@property (nonatomic, copy) NSString * _Null_unspecified certificatePath;
@property (nonatomic, copy) NSString * _Null_unspecified certificatePassword;
@property (nonatomic, strong) NSURLAuthenticationChallenge * _Null_unspecified challenge;
- (nonnull instancetype)initWithClientSSLCertificate:(NSString * _Nonnull)certificatePath password:(NSString * _Nonnull)password completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler OBJC_DESIGNATED_INITIALIZER;
- (void)handleServerTrustChallenge;
- (void)handleClientTrustChallenge;
- (void)connection:(NSURLConnection * _Nonnull)connection willSendRequestForAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge;
- (void)connection:(NSURLConnection * _Nonnull)connection didReceiveResponse:(NSURLResponse * _Nonnull)response;
- (void)connection:(NSURLConnection * _Nonnull)connection didReceiveData:(NSData * _Nonnull)data;
- (void)connectionDidFinishLoading:(NSURLConnection * _Nonnull)connection;
- (void)connection:(NSURLConnection * _Nonnull)connection didFailWithError:(NSError * _Nonnull)error;
- (void)connection:(NSURLConnection * _Nonnull)connection didCancelAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PGOrder;

SWIFT_CLASS("_TtC10PaymentSDK23PGMerchantConfiguration")
@interface PGMerchantConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) PGMerchantConfiguration * _Nonnull defaultMerchantObject;)
+ (PGMerchantConfiguration * _Nonnull)defaultMerchantObject SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultMerchantObject:(PGMerchantConfiguration * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger onceConfiguration;)
+ (NSInteger)onceConfiguration SWIFT_WARN_UNUSED_RESULT;
+ (void)setOnceConfiguration:(NSInteger)value;
@property (nonatomic, copy) NSString * _Nonnull merchantID;
@property (nonatomic, copy) NSString * _Nonnull website;
@property (nonatomic, copy) NSString * _Nonnull industryID;
@property (nonatomic, copy) NSString * _Nonnull channelID;
@property (nonatomic, copy) NSString * _Nonnull theme;
@property (nonatomic, copy) NSString * _Nonnull authMode;
@property (nonatomic, copy) NSString * _Nonnull paymentTypeID;
@property (nonatomic, copy) NSString * _Nonnull cardType;
@property (nonatomic, copy) NSString * _Nonnull bankCode;
@property (nonatomic, copy) NSString * _Null_unspecified clientSSLCertPath;
@property (nonatomic, copy) NSString * _Null_unspecified clientSSLCertPassword;
@property (nonatomic, copy) NSString * _Nonnull checksumGenerationURL;
@property (nonatomic, copy) NSString * _Nonnull checksumValidationURL;
+ (PGMerchantConfiguration * _Nonnull)defaultConfiguration SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)transactionParametersFor:(PGOrder * _Nonnull)order SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, PGMerchantVerificationStatus, open) {
  PGMerchantVerificationStatusKCASVerificationStatusUndefined = 0,
  PGMerchantVerificationStatusKCASVerificationStatusSuccess = 1,
  PGMerchantVerificationStatusKCASVerificationStatusFailed = 2,
};

@class NSCoder;

SWIFT_CLASS("_TtC10PaymentSDK7PGOrder")
@interface PGOrder : NSObject
@property (nonatomic, copy) NSString * _Nonnull orderID;
@property (nonatomic, copy) NSString * _Nonnull customerID;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull eMail;
@property (nonatomic, copy) NSString * _Nonnull mobile;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull params;
- (nonnull instancetype)initWithOrderID:(NSString * _Nonnull)orderID customerID:(NSString * _Nonnull)customerID amount:(NSString * _Nonnull)amount eMail:(NSString * _Nonnull)eMail mobile:(NSString * _Nonnull)mobile;
- (void)encodeWithCoderWithACoder:(NSCoder * _Nonnull)aCoder;
- (NSDictionary<NSString *, NSString *> * _Nonnull)orderWithParamsWithDic:(NSDictionary<NSString *, NSString *> * _Nonnull)dic SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ServerType : NSInteger;
@class UIView;

SWIFT_CLASS("_TtC10PaymentSDK19PGServerEnvironment")
@interface PGServerEnvironment : NSObject
@property (nonatomic, copy) NSString * _Nonnull clientAuthURL;
@property (nonatomic, copy) NSString * _Null_unspecified paymentGatewayURL;
@property (nonatomic, copy) NSString * _Nonnull statusQueryURL;
@property (nonatomic, copy) NSString * _Nonnull refundURL;
@property (nonatomic, copy) NSString * _Nonnull cancelTransactionURL;
@property (nonatomic, copy) NSString * _Nonnull callBackURLFormat;
@property (nonatomic, copy) NSString * _Nonnull checksumValidationURL;
@property (nonatomic) BOOL isProduction;
@property (nonatomic) BOOL servrEnvironmentCreated;
@property (nonatomic, strong) PGServerEnvironment * _Null_unspecified currentServer;
@property (nonatomic, copy) void (^ _Nullable serverSelectionDialogHandler)(enum ServerType);
- (PGServerEnvironment * _Nonnull)createStagingEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGServerEnvironment * _Nonnull)createProductionEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGServerEnvironment * _Nonnull)currentServerEnvironment SWIFT_WARN_UNUSED_RESULT;
- (BOOL)serverEnvironmentCreated SWIFT_WARN_UNUSED_RESULT;
- (void)selectServerDialog:(UIView * _Nonnull)parentView completionHandler:(void (^ _Nonnull)(enum ServerType))handler;
- (void)statusForOrderIDWithOrderID:(NSString * _Nonnull)orderID responseHandler:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
- (NSString * _Nonnull)domain SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PGTransactionViewController;

SWIFT_PROTOCOL("_TtP10PaymentSDK21PGTransactionDelegate_")
@protocol PGTransactionDelegate
- (void)didFinishedResponse:(PGTransactionViewController * _Nonnull)controller response:(NSString * _Nonnull)responseString;
- (void)didCancelTrasaction:(PGTransactionViewController * _Nonnull)controller;
- (void)errorMisssingParameter:(PGTransactionViewController * _Nonnull)controller error:(NSError * _Nullable)error;
@end

@class WKWebView;
@class NSMutableURLRequest;
@class UIButton;
@class NSBundle;

SWIFT_CLASS("_TtC10PaymentSDK27PGTransactionViewController")
@interface PGTransactionViewController : UIViewController <UIActionSheetDelegate>
@property (nonatomic, strong) PGServerEnvironment * _Nonnull server;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull txnParameters;
@property (nonatomic, copy) NSDictionary * _Nonnull clientAuthServerResponseDict;
@property (nonatomic, strong) WKWebView * _Nullable webView;
@property (nonatomic, strong) NSMutableURLRequest * _Nullable pgRequest;
@property (nonatomic) BOOL isNavigationBarHiddenState;
@property (nonatomic, strong) id <PGTransactionDelegate> _Nullable delegate;
@property (nonatomic) BOOL useStaging;
@property (nonatomic) BOOL isLoggingEnabled;
@property (nonatomic) enum ServerType serverType;
@property (nonatomic, strong) PGMerchantConfiguration * _Nullable merchant;
@property (nonatomic) BOOL sendAllChecksumResponseParamsToPG;
@property (nonatomic, strong) UIView * _Nonnull topBar;
@property (nonatomic, strong) UIButton * _Nonnull cancelButton;
- (nonnull instancetype)initWithTransactionParameters:(NSDictionary<NSString *, id> * _Nonnull)parameters;
- (id _Nonnull)initTransactionFor:(PGOrder * _Nonnull)orderObj SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)loadView;
- (BOOL)isValidRequest SWIFT_WARN_UNUSED_RESULT;
- (void)cancel:(id _Nullable)sender;
- (void)setLoggingEnabled:(BOOL)enabled;
- (void)showProgress:(NSString * _Nonnull)progressString;
- (void)hideProgress;
- (void)didReceiveMemoryWarning;
- (void)finishedResponse:(NSString * _Nonnull)response;
- (void)missingParameter:(NSError * _Nullable)error;
- (void)failedCallback:(NSError * _Nullable)error response:(NSDictionary * _Nonnull)dict;
- (void)successCallback:(NSError * _Nullable)error response:(NSDictionary * _Nonnull)dict;
- (void)cancelCallback;
- (void)beginPGTransaction;
- (void)loadAuthenticatedRequestInWebView;
- (void)pgTransactionEndedWithResponseJSON:(NSString * _Nonnull)json urlEncodedString:(NSString * _Nonnull)urlEncoded;
- (void)cancelCurrentTransaction;
- (void)cleanup;
- (BOOL)isLoadingCallbackURL:(NSString * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (void)validateMerchantChecksum:(NSDictionary * _Nonnull)parms;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKFrameInfo;

@interface PGTransactionViewController (SWIFT_EXTENSION(PaymentSDK)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)runJavaScriptAlertPanelWithMessage initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)runJavaScriptConfirmPanelWithMessage initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)runJavaScriptTextInputPanelWithPrompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
@end

@class WKNavigation;
@class WKNavigationAction;

@interface PGTransactionViewController (SWIFT_EXTENSION(PaymentSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC10PaymentSDK7PGUtils")
@interface PGUtils : NSObject
@property (nonatomic, strong) PGConnectionDelegate * _Null_unspecified delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PGUtils * _Nonnull sharedInstance;)
+ (PGUtils * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogStatus:(BOOL)status;
+ (NSString * _Nonnull)dictionaryToURLEncodedStringWithDict:(NSDictionary * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)dictionaryFromURLEncodedStringWithUrlEncodedString:(NSString * _Nonnull)urlEncodedString SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)dictionaryFromJsonStringWithJsonString:(NSString * _Nonnull)jsonString SWIFT_WARN_UNUSED_RESULT;
+ (OSStatus)extractIdentity:(NSData * _Nonnull)certData SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)noInternetError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)checksumVerificationError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)nilChecksumValidationURL SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)missingParametrs:(NSString * _Nonnull)errorMessage SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)emptyDataError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorForResponseCodeWithResponseCodeStr:(NSString * _Nonnull)responseCodeStr SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorForHTTPCodeWithCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)pgResponseCodes SWIFT_WARN_UNUSED_RESULT;
+ (NSURLRequest * _Nonnull)requestForURLWithUrl:(NSString * _Nonnull)url withParms:(NSDictionary * _Nonnull)parms SWIFT_WARN_UNUSED_RESULT;
+ (void)postToURL:(NSString * _Nonnull)url with:(NSString * _Nonnull)value completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
+ (void)postToURL:(NSString * _Nonnull)URL withParms:(NSDictionary * _Nonnull)parms completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
- (void)makeConnectionWith:(NSMutableURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ServerType, open) {
  ServerTypeEServerTypeProduction = 0,
  ServerTypeEServerTypeStaging = 1,
  ServerTypeEServerTypeNone = 2,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Darwin;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PaymentSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC10PaymentSDK24AlertControllerWithBlock")
@interface AlertControllerWithBlock : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSHTTPURLResponse;
@class NSData;
@class NSError;
@class NSURLConnection;
@class NSURLAuthenticationChallenge;
@class NSURLResponse;

SWIFT_CLASS("_TtC10PaymentSDK20PGConnectionDelegate")
@interface PGConnectionDelegate : NSObject <NSURLConnectionDataDelegate>
@property (nonatomic) BOOL ignoreServerTrust;
@property (nonatomic, strong) NSHTTPURLResponse * _Null_unspecified response;
@property (nonatomic, strong) NSData * _Null_unspecified data;
@property (nonatomic, strong) NSError * _Null_unspecified error;
@property (nonatomic, strong) NSURLConnection * _Null_unspecified connection;
@property (nonatomic, copy) void (^ _Nullable completionHandler)(PGConnectionDelegate * _Nonnull);
@property (nonatomic, copy) NSString * _Null_unspecified certificatePath;
@property (nonatomic, copy) NSString * _Null_unspecified certificatePassword;
@property (nonatomic, strong) NSURLAuthenticationChallenge * _Null_unspecified challenge;
- (nonnull instancetype)initWithClientSSLCertificate:(NSString * _Nonnull)certificatePath password:(NSString * _Nonnull)password completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler OBJC_DESIGNATED_INITIALIZER;
- (void)handleServerTrustChallenge;
- (void)handleClientTrustChallenge;
- (void)connection:(NSURLConnection * _Nonnull)connection willSendRequestForAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge;
- (void)connection:(NSURLConnection * _Nonnull)connection didReceiveResponse:(NSURLResponse * _Nonnull)response;
- (void)connection:(NSURLConnection * _Nonnull)connection didReceiveData:(NSData * _Nonnull)data;
- (void)connectionDidFinishLoading:(NSURLConnection * _Nonnull)connection;
- (void)connection:(NSURLConnection * _Nonnull)connection didFailWithError:(NSError * _Nonnull)error;
- (void)connection:(NSURLConnection * _Nonnull)connection didCancelAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PGOrder;

SWIFT_CLASS("_TtC10PaymentSDK23PGMerchantConfiguration")
@interface PGMerchantConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) PGMerchantConfiguration * _Nonnull defaultMerchantObject;)
+ (PGMerchantConfiguration * _Nonnull)defaultMerchantObject SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultMerchantObject:(PGMerchantConfiguration * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger onceConfiguration;)
+ (NSInteger)onceConfiguration SWIFT_WARN_UNUSED_RESULT;
+ (void)setOnceConfiguration:(NSInteger)value;
@property (nonatomic, copy) NSString * _Nonnull merchantID;
@property (nonatomic, copy) NSString * _Nonnull website;
@property (nonatomic, copy) NSString * _Nonnull industryID;
@property (nonatomic, copy) NSString * _Nonnull channelID;
@property (nonatomic, copy) NSString * _Nonnull theme;
@property (nonatomic, copy) NSString * _Nonnull authMode;
@property (nonatomic, copy) NSString * _Nonnull paymentTypeID;
@property (nonatomic, copy) NSString * _Nonnull cardType;
@property (nonatomic, copy) NSString * _Nonnull bankCode;
@property (nonatomic, copy) NSString * _Null_unspecified clientSSLCertPath;
@property (nonatomic, copy) NSString * _Null_unspecified clientSSLCertPassword;
@property (nonatomic, copy) NSString * _Nonnull checksumGenerationURL;
@property (nonatomic, copy) NSString * _Nonnull checksumValidationURL;
+ (PGMerchantConfiguration * _Nonnull)defaultConfiguration SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)transactionParametersFor:(PGOrder * _Nonnull)order SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, PGMerchantVerificationStatus, open) {
  PGMerchantVerificationStatusKCASVerificationStatusUndefined = 0,
  PGMerchantVerificationStatusKCASVerificationStatusSuccess = 1,
  PGMerchantVerificationStatusKCASVerificationStatusFailed = 2,
};

@class NSCoder;

SWIFT_CLASS("_TtC10PaymentSDK7PGOrder")
@interface PGOrder : NSObject
@property (nonatomic, copy) NSString * _Nonnull orderID;
@property (nonatomic, copy) NSString * _Nonnull customerID;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull eMail;
@property (nonatomic, copy) NSString * _Nonnull mobile;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull params;
- (nonnull instancetype)initWithOrderID:(NSString * _Nonnull)orderID customerID:(NSString * _Nonnull)customerID amount:(NSString * _Nonnull)amount eMail:(NSString * _Nonnull)eMail mobile:(NSString * _Nonnull)mobile;
- (void)encodeWithCoderWithACoder:(NSCoder * _Nonnull)aCoder;
- (NSDictionary<NSString *, NSString *> * _Nonnull)orderWithParamsWithDic:(NSDictionary<NSString *, NSString *> * _Nonnull)dic SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ServerType : NSInteger;
@class UIView;

SWIFT_CLASS("_TtC10PaymentSDK19PGServerEnvironment")
@interface PGServerEnvironment : NSObject
@property (nonatomic, copy) NSString * _Nonnull clientAuthURL;
@property (nonatomic, copy) NSString * _Null_unspecified paymentGatewayURL;
@property (nonatomic, copy) NSString * _Nonnull statusQueryURL;
@property (nonatomic, copy) NSString * _Nonnull refundURL;
@property (nonatomic, copy) NSString * _Nonnull cancelTransactionURL;
@property (nonatomic, copy) NSString * _Nonnull callBackURLFormat;
@property (nonatomic, copy) NSString * _Nonnull checksumValidationURL;
@property (nonatomic) BOOL isProduction;
@property (nonatomic) BOOL servrEnvironmentCreated;
@property (nonatomic, strong) PGServerEnvironment * _Null_unspecified currentServer;
@property (nonatomic, copy) void (^ _Nullable serverSelectionDialogHandler)(enum ServerType);
- (PGServerEnvironment * _Nonnull)createStagingEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGServerEnvironment * _Nonnull)createProductionEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGServerEnvironment * _Nonnull)currentServerEnvironment SWIFT_WARN_UNUSED_RESULT;
- (BOOL)serverEnvironmentCreated SWIFT_WARN_UNUSED_RESULT;
- (void)selectServerDialog:(UIView * _Nonnull)parentView completionHandler:(void (^ _Nonnull)(enum ServerType))handler;
- (void)statusForOrderIDWithOrderID:(NSString * _Nonnull)orderID responseHandler:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
- (NSString * _Nonnull)domain SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PGTransactionViewController;

SWIFT_PROTOCOL("_TtP10PaymentSDK21PGTransactionDelegate_")
@protocol PGTransactionDelegate
- (void)didFinishedResponse:(PGTransactionViewController * _Nonnull)controller response:(NSString * _Nonnull)responseString;
- (void)didCancelTrasaction:(PGTransactionViewController * _Nonnull)controller;
- (void)errorMisssingParameter:(PGTransactionViewController * _Nonnull)controller error:(NSError * _Nullable)error;
@end

@class WKWebView;
@class NSMutableURLRequest;
@class UIButton;
@class NSBundle;

SWIFT_CLASS("_TtC10PaymentSDK27PGTransactionViewController")
@interface PGTransactionViewController : UIViewController <UIActionSheetDelegate>
@property (nonatomic, strong) PGServerEnvironment * _Nonnull server;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull txnParameters;
@property (nonatomic, copy) NSDictionary * _Nonnull clientAuthServerResponseDict;
@property (nonatomic, strong) WKWebView * _Nullable webView;
@property (nonatomic, strong) NSMutableURLRequest * _Nullable pgRequest;
@property (nonatomic) BOOL isNavigationBarHiddenState;
@property (nonatomic, strong) id <PGTransactionDelegate> _Nullable delegate;
@property (nonatomic) BOOL useStaging;
@property (nonatomic) BOOL isLoggingEnabled;
@property (nonatomic) enum ServerType serverType;
@property (nonatomic, strong) PGMerchantConfiguration * _Nullable merchant;
@property (nonatomic) BOOL sendAllChecksumResponseParamsToPG;
@property (nonatomic, strong) UIView * _Nonnull topBar;
@property (nonatomic, strong) UIButton * _Nonnull cancelButton;
- (nonnull instancetype)initWithTransactionParameters:(NSDictionary<NSString *, id> * _Nonnull)parameters;
- (id _Nonnull)initTransactionFor:(PGOrder * _Nonnull)orderObj SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)loadView;
- (BOOL)isValidRequest SWIFT_WARN_UNUSED_RESULT;
- (void)cancel:(id _Nullable)sender;
- (void)setLoggingEnabled:(BOOL)enabled;
- (void)showProgress:(NSString * _Nonnull)progressString;
- (void)hideProgress;
- (void)didReceiveMemoryWarning;
- (void)finishedResponse:(NSString * _Nonnull)response;
- (void)missingParameter:(NSError * _Nullable)error;
- (void)failedCallback:(NSError * _Nullable)error response:(NSDictionary * _Nonnull)dict;
- (void)successCallback:(NSError * _Nullable)error response:(NSDictionary * _Nonnull)dict;
- (void)cancelCallback;
- (void)beginPGTransaction;
- (void)loadAuthenticatedRequestInWebView;
- (void)pgTransactionEndedWithResponseJSON:(NSString * _Nonnull)json urlEncodedString:(NSString * _Nonnull)urlEncoded;
- (void)cancelCurrentTransaction;
- (void)cleanup;
- (BOOL)isLoadingCallbackURL:(NSString * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (void)validateMerchantChecksum:(NSDictionary * _Nonnull)parms;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKFrameInfo;

@interface PGTransactionViewController (SWIFT_EXTENSION(PaymentSDK)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)runJavaScriptAlertPanelWithMessage initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)runJavaScriptConfirmPanelWithMessage initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)runJavaScriptTextInputPanelWithPrompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
@end

@class WKNavigation;
@class WKNavigationAction;

@interface PGTransactionViewController (SWIFT_EXTENSION(PaymentSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC10PaymentSDK7PGUtils")
@interface PGUtils : NSObject
@property (nonatomic, strong) PGConnectionDelegate * _Null_unspecified delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PGUtils * _Nonnull sharedInstance;)
+ (PGUtils * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogStatus:(BOOL)status;
+ (NSString * _Nonnull)dictionaryToURLEncodedStringWithDict:(NSDictionary * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)dictionaryFromURLEncodedStringWithUrlEncodedString:(NSString * _Nonnull)urlEncodedString SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)dictionaryFromJsonStringWithJsonString:(NSString * _Nonnull)jsonString SWIFT_WARN_UNUSED_RESULT;
+ (OSStatus)extractIdentity:(NSData * _Nonnull)certData SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)noInternetError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)checksumVerificationError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)nilChecksumValidationURL SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)missingParametrs:(NSString * _Nonnull)errorMessage SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)emptyDataError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorForResponseCodeWithResponseCodeStr:(NSString * _Nonnull)responseCodeStr SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorForHTTPCodeWithCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)pgResponseCodes SWIFT_WARN_UNUSED_RESULT;
+ (NSURLRequest * _Nonnull)requestForURLWithUrl:(NSString * _Nonnull)url withParms:(NSDictionary * _Nonnull)parms SWIFT_WARN_UNUSED_RESULT;
+ (void)postToURL:(NSString * _Nonnull)url with:(NSString * _Nonnull)value completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
+ (void)postToURL:(NSString * _Nonnull)URL withParms:(NSDictionary * _Nonnull)parms completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
- (void)makeConnectionWith:(NSMutableURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ServerType, open) {
  ServerTypeEServerTypeProduction = 0,
  ServerTypeEServerTypeStaging = 1,
  ServerTypeEServerTypeNone = 2,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif


#else

#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Darwin;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PaymentSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC10PaymentSDK24AlertControllerWithBlock")
@interface AlertControllerWithBlock : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSHTTPURLResponse;
@class NSData;
@class NSError;
@class NSURLConnection;
@class NSURLAuthenticationChallenge;
@class NSURLResponse;

SWIFT_CLASS("_TtC10PaymentSDK20PGConnectionDelegate")
@interface PGConnectionDelegate : NSObject <NSURLConnectionDataDelegate>
@property (nonatomic) BOOL ignoreServerTrust;
@property (nonatomic, strong) NSHTTPURLResponse * _Null_unspecified response;
@property (nonatomic, strong) NSData * _Null_unspecified data;
@property (nonatomic, strong) NSError * _Null_unspecified error;
@property (nonatomic, strong) NSURLConnection * _Null_unspecified connection;
@property (nonatomic, copy) void (^ _Nullable completionHandler)(PGConnectionDelegate * _Nonnull);
@property (nonatomic, copy) NSString * _Null_unspecified certificatePath;
@property (nonatomic, copy) NSString * _Null_unspecified certificatePassword;
@property (nonatomic, strong) NSURLAuthenticationChallenge * _Null_unspecified challenge;
- (nonnull instancetype)initWithClientSSLCertificate:(NSString * _Nonnull)certificatePath password:(NSString * _Nonnull)password completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler OBJC_DESIGNATED_INITIALIZER;
- (void)handleServerTrustChallenge;
- (void)handleClientTrustChallenge;
- (void)connection:(NSURLConnection * _Nonnull)connection willSendRequestForAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge;
- (void)connection:(NSURLConnection * _Nonnull)connection didReceiveResponse:(NSURLResponse * _Nonnull)response;
- (void)connection:(NSURLConnection * _Nonnull)connection didReceiveData:(NSData * _Nonnull)data;
- (void)connectionDidFinishLoading:(NSURLConnection * _Nonnull)connection;
- (void)connection:(NSURLConnection * _Nonnull)connection didFailWithError:(NSError * _Nonnull)error;
- (void)connection:(NSURLConnection * _Nonnull)connection didCancelAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PGOrder;

SWIFT_CLASS("_TtC10PaymentSDK23PGMerchantConfiguration")
@interface PGMerchantConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) PGMerchantConfiguration * _Nonnull defaultMerchantObject;)
+ (PGMerchantConfiguration * _Nonnull)defaultMerchantObject SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultMerchantObject:(PGMerchantConfiguration * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger onceConfiguration;)
+ (NSInteger)onceConfiguration SWIFT_WARN_UNUSED_RESULT;
+ (void)setOnceConfiguration:(NSInteger)value;
@property (nonatomic, copy) NSString * _Nonnull merchantID;
@property (nonatomic, copy) NSString * _Nonnull website;
@property (nonatomic, copy) NSString * _Nonnull industryID;
@property (nonatomic, copy) NSString * _Nonnull channelID;
@property (nonatomic, copy) NSString * _Nonnull theme;
@property (nonatomic, copy) NSString * _Nonnull authMode;
@property (nonatomic, copy) NSString * _Nonnull paymentTypeID;
@property (nonatomic, copy) NSString * _Nonnull cardType;
@property (nonatomic, copy) NSString * _Nonnull bankCode;
@property (nonatomic, copy) NSString * _Null_unspecified clientSSLCertPath;
@property (nonatomic, copy) NSString * _Null_unspecified clientSSLCertPassword;
@property (nonatomic, copy) NSString * _Nonnull checksumGenerationURL;
@property (nonatomic, copy) NSString * _Nonnull checksumValidationURL;
+ (PGMerchantConfiguration * _Nonnull)defaultConfiguration SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)transactionParametersFor:(PGOrder * _Nonnull)order SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, PGMerchantVerificationStatus, open) {
  PGMerchantVerificationStatusKCASVerificationStatusUndefined = 0,
  PGMerchantVerificationStatusKCASVerificationStatusSuccess = 1,
  PGMerchantVerificationStatusKCASVerificationStatusFailed = 2,
};

@class NSCoder;

SWIFT_CLASS("_TtC10PaymentSDK7PGOrder")
@interface PGOrder : NSObject
@property (nonatomic, copy) NSString * _Nonnull orderID;
@property (nonatomic, copy) NSString * _Nonnull customerID;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull eMail;
@property (nonatomic, copy) NSString * _Nonnull mobile;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull params;
- (nonnull instancetype)initWithOrderID:(NSString * _Nonnull)orderID customerID:(NSString * _Nonnull)customerID amount:(NSString * _Nonnull)amount eMail:(NSString * _Nonnull)eMail mobile:(NSString * _Nonnull)mobile;
- (void)encodeWithCoderWithACoder:(NSCoder * _Nonnull)aCoder;
- (NSDictionary<NSString *, NSString *> * _Nonnull)orderWithParamsWithDic:(NSDictionary<NSString *, NSString *> * _Nonnull)dic SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ServerType : NSInteger;
@class UIView;

SWIFT_CLASS("_TtC10PaymentSDK19PGServerEnvironment")
@interface PGServerEnvironment : NSObject
@property (nonatomic, copy) NSString * _Nonnull clientAuthURL;
@property (nonatomic, copy) NSString * _Null_unspecified paymentGatewayURL;
@property (nonatomic, copy) NSString * _Nonnull statusQueryURL;
@property (nonatomic, copy) NSString * _Nonnull refundURL;
@property (nonatomic, copy) NSString * _Nonnull cancelTransactionURL;
@property (nonatomic, copy) NSString * _Nonnull callBackURLFormat;
@property (nonatomic, copy) NSString * _Nonnull checksumValidationURL;
@property (nonatomic) BOOL isProduction;
@property (nonatomic) BOOL servrEnvironmentCreated;
@property (nonatomic, strong) PGServerEnvironment * _Null_unspecified currentServer;
@property (nonatomic, copy) void (^ _Nullable serverSelectionDialogHandler)(enum ServerType);
- (PGServerEnvironment * _Nonnull)createStagingEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGServerEnvironment * _Nonnull)createProductionEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGServerEnvironment * _Nonnull)currentServerEnvironment SWIFT_WARN_UNUSED_RESULT;
- (BOOL)serverEnvironmentCreated SWIFT_WARN_UNUSED_RESULT;
- (void)selectServerDialog:(UIView * _Nonnull)parentView completionHandler:(void (^ _Nonnull)(enum ServerType))handler;
- (void)statusForOrderIDWithOrderID:(NSString * _Nonnull)orderID responseHandler:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
- (NSString * _Nonnull)domain SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PGTransactionViewController;

SWIFT_PROTOCOL("_TtP10PaymentSDK21PGTransactionDelegate_")
@protocol PGTransactionDelegate
- (void)didFinishedResponse:(PGTransactionViewController * _Nonnull)controller response:(NSString * _Nonnull)responseString;
- (void)didCancelTrasaction:(PGTransactionViewController * _Nonnull)controller;
- (void)errorMisssingParameter:(PGTransactionViewController * _Nonnull)controller error:(NSError * _Nullable)error;
@end

@class WKWebView;
@class NSMutableURLRequest;
@class UIButton;
@class NSBundle;

SWIFT_CLASS("_TtC10PaymentSDK27PGTransactionViewController")
@interface PGTransactionViewController : UIViewController <UIActionSheetDelegate>
@property (nonatomic, strong) PGServerEnvironment * _Nonnull server;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull txnParameters;
@property (nonatomic, copy) NSDictionary * _Nonnull clientAuthServerResponseDict;
@property (nonatomic, strong) WKWebView * _Nullable webView;
@property (nonatomic, strong) NSMutableURLRequest * _Nullable pgRequest;
@property (nonatomic) BOOL isNavigationBarHiddenState;
@property (nonatomic, strong) id <PGTransactionDelegate> _Nullable delegate;
@property (nonatomic) BOOL useStaging;
@property (nonatomic) BOOL isLoggingEnabled;
@property (nonatomic) enum ServerType serverType;
@property (nonatomic, strong) PGMerchantConfiguration * _Nullable merchant;
@property (nonatomic) BOOL sendAllChecksumResponseParamsToPG;
@property (nonatomic, strong) UIView * _Nonnull topBar;
@property (nonatomic, strong) UIButton * _Nonnull cancelButton;
- (nonnull instancetype)initWithTransactionParameters:(NSDictionary<NSString *, id> * _Nonnull)parameters;
- (id _Nonnull)initTransactionFor:(PGOrder * _Nonnull)orderObj SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)loadView;
- (BOOL)isValidRequest SWIFT_WARN_UNUSED_RESULT;
- (void)cancel:(id _Nullable)sender;
- (void)setLoggingEnabled:(BOOL)enabled;
- (void)showProgress:(NSString * _Nonnull)progressString;
- (void)hideProgress;
- (void)didReceiveMemoryWarning;
- (void)finishedResponse:(NSString * _Nonnull)response;
- (void)missingParameter:(NSError * _Nullable)error;
- (void)failedCallback:(NSError * _Nullable)error response:(NSDictionary * _Nonnull)dict;
- (void)successCallback:(NSError * _Nullable)error response:(NSDictionary * _Nonnull)dict;
- (void)cancelCallback;
- (void)beginPGTransaction;
- (void)loadAuthenticatedRequestInWebView;
- (void)pgTransactionEndedWithResponseJSON:(NSString * _Nonnull)json urlEncodedString:(NSString * _Nonnull)urlEncoded;
- (void)cancelCurrentTransaction;
- (void)cleanup;
- (BOOL)isLoadingCallbackURL:(NSString * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (void)validateMerchantChecksum:(NSDictionary * _Nonnull)parms;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKFrameInfo;

@interface PGTransactionViewController (SWIFT_EXTENSION(PaymentSDK)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)runJavaScriptAlertPanelWithMessage initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)runJavaScriptConfirmPanelWithMessage initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)runJavaScriptTextInputPanelWithPrompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
@end

@class WKNavigation;
@class WKNavigationAction;

@interface PGTransactionViewController (SWIFT_EXTENSION(PaymentSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC10PaymentSDK7PGUtils")
@interface PGUtils : NSObject
@property (nonatomic, strong) PGConnectionDelegate * _Null_unspecified delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PGUtils * _Nonnull sharedInstance;)
+ (PGUtils * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogStatus:(BOOL)status;
+ (NSString * _Nonnull)dictionaryToURLEncodedStringWithDict:(NSDictionary * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)dictionaryFromURLEncodedStringWithUrlEncodedString:(NSString * _Nonnull)urlEncodedString SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)dictionaryFromJsonStringWithJsonString:(NSString * _Nonnull)jsonString SWIFT_WARN_UNUSED_RESULT;
+ (OSStatus)extractIdentity:(NSData * _Nonnull)certData SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)noInternetError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)checksumVerificationError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)nilChecksumValidationURL SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)missingParametrs:(NSString * _Nonnull)errorMessage SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)emptyDataError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorForResponseCodeWithResponseCodeStr:(NSString * _Nonnull)responseCodeStr SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorForHTTPCodeWithCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)pgResponseCodes SWIFT_WARN_UNUSED_RESULT;
+ (NSURLRequest * _Nonnull)requestForURLWithUrl:(NSString * _Nonnull)url withParms:(NSDictionary * _Nonnull)parms SWIFT_WARN_UNUSED_RESULT;
+ (void)postToURL:(NSString * _Nonnull)url with:(NSString * _Nonnull)value completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
+ (void)postToURL:(NSString * _Nonnull)URL withParms:(NSDictionary * _Nonnull)parms completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
- (void)makeConnectionWith:(NSMutableURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ServerType, open) {
  ServerTypeEServerTypeProduction = 0,
  ServerTypeEServerTypeStaging = 1,
  ServerTypeEServerTypeNone = 2,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Darwin;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PaymentSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC10PaymentSDK24AlertControllerWithBlock")
@interface AlertControllerWithBlock : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSHTTPURLResponse;
@class NSData;
@class NSError;
@class NSURLConnection;
@class NSURLAuthenticationChallenge;
@class NSURLResponse;

SWIFT_CLASS("_TtC10PaymentSDK20PGConnectionDelegate")
@interface PGConnectionDelegate : NSObject <NSURLConnectionDataDelegate>
@property (nonatomic) BOOL ignoreServerTrust;
@property (nonatomic, strong) NSHTTPURLResponse * _Null_unspecified response;
@property (nonatomic, strong) NSData * _Null_unspecified data;
@property (nonatomic, strong) NSError * _Null_unspecified error;
@property (nonatomic, strong) NSURLConnection * _Null_unspecified connection;
@property (nonatomic, copy) void (^ _Nullable completionHandler)(PGConnectionDelegate * _Nonnull);
@property (nonatomic, copy) NSString * _Null_unspecified certificatePath;
@property (nonatomic, copy) NSString * _Null_unspecified certificatePassword;
@property (nonatomic, strong) NSURLAuthenticationChallenge * _Null_unspecified challenge;
- (nonnull instancetype)initWithClientSSLCertificate:(NSString * _Nonnull)certificatePath password:(NSString * _Nonnull)password completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler OBJC_DESIGNATED_INITIALIZER;
- (void)handleServerTrustChallenge;
- (void)handleClientTrustChallenge;
- (void)connection:(NSURLConnection * _Nonnull)connection willSendRequestForAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge;
- (void)connection:(NSURLConnection * _Nonnull)connection didReceiveResponse:(NSURLResponse * _Nonnull)response;
- (void)connection:(NSURLConnection * _Nonnull)connection didReceiveData:(NSData * _Nonnull)data;
- (void)connectionDidFinishLoading:(NSURLConnection * _Nonnull)connection;
- (void)connection:(NSURLConnection * _Nonnull)connection didFailWithError:(NSError * _Nonnull)error;
- (void)connection:(NSURLConnection * _Nonnull)connection didCancelAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PGOrder;

SWIFT_CLASS("_TtC10PaymentSDK23PGMerchantConfiguration")
@interface PGMerchantConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) PGMerchantConfiguration * _Nonnull defaultMerchantObject;)
+ (PGMerchantConfiguration * _Nonnull)defaultMerchantObject SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultMerchantObject:(PGMerchantConfiguration * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger onceConfiguration;)
+ (NSInteger)onceConfiguration SWIFT_WARN_UNUSED_RESULT;
+ (void)setOnceConfiguration:(NSInteger)value;
@property (nonatomic, copy) NSString * _Nonnull merchantID;
@property (nonatomic, copy) NSString * _Nonnull website;
@property (nonatomic, copy) NSString * _Nonnull industryID;
@property (nonatomic, copy) NSString * _Nonnull channelID;
@property (nonatomic, copy) NSString * _Nonnull theme;
@property (nonatomic, copy) NSString * _Nonnull authMode;
@property (nonatomic, copy) NSString * _Nonnull paymentTypeID;
@property (nonatomic, copy) NSString * _Nonnull cardType;
@property (nonatomic, copy) NSString * _Nonnull bankCode;
@property (nonatomic, copy) NSString * _Null_unspecified clientSSLCertPath;
@property (nonatomic, copy) NSString * _Null_unspecified clientSSLCertPassword;
@property (nonatomic, copy) NSString * _Nonnull checksumGenerationURL;
@property (nonatomic, copy) NSString * _Nonnull checksumValidationURL;
+ (PGMerchantConfiguration * _Nonnull)defaultConfiguration SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)transactionParametersFor:(PGOrder * _Nonnull)order SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, PGMerchantVerificationStatus, open) {
  PGMerchantVerificationStatusKCASVerificationStatusUndefined = 0,
  PGMerchantVerificationStatusKCASVerificationStatusSuccess = 1,
  PGMerchantVerificationStatusKCASVerificationStatusFailed = 2,
};

@class NSCoder;

SWIFT_CLASS("_TtC10PaymentSDK7PGOrder")
@interface PGOrder : NSObject
@property (nonatomic, copy) NSString * _Nonnull orderID;
@property (nonatomic, copy) NSString * _Nonnull customerID;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull eMail;
@property (nonatomic, copy) NSString * _Nonnull mobile;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull params;
- (nonnull instancetype)initWithOrderID:(NSString * _Nonnull)orderID customerID:(NSString * _Nonnull)customerID amount:(NSString * _Nonnull)amount eMail:(NSString * _Nonnull)eMail mobile:(NSString * _Nonnull)mobile;
- (void)encodeWithCoderWithACoder:(NSCoder * _Nonnull)aCoder;
- (NSDictionary<NSString *, NSString *> * _Nonnull)orderWithParamsWithDic:(NSDictionary<NSString *, NSString *> * _Nonnull)dic SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ServerType : NSInteger;
@class UIView;

SWIFT_CLASS("_TtC10PaymentSDK19PGServerEnvironment")
@interface PGServerEnvironment : NSObject
@property (nonatomic, copy) NSString * _Nonnull clientAuthURL;
@property (nonatomic, copy) NSString * _Null_unspecified paymentGatewayURL;
@property (nonatomic, copy) NSString * _Nonnull statusQueryURL;
@property (nonatomic, copy) NSString * _Nonnull refundURL;
@property (nonatomic, copy) NSString * _Nonnull cancelTransactionURL;
@property (nonatomic, copy) NSString * _Nonnull callBackURLFormat;
@property (nonatomic, copy) NSString * _Nonnull checksumValidationURL;
@property (nonatomic) BOOL isProduction;
@property (nonatomic) BOOL servrEnvironmentCreated;
@property (nonatomic, strong) PGServerEnvironment * _Null_unspecified currentServer;
@property (nonatomic, copy) void (^ _Nullable serverSelectionDialogHandler)(enum ServerType);
- (PGServerEnvironment * _Nonnull)createStagingEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGServerEnvironment * _Nonnull)createProductionEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGServerEnvironment * _Nonnull)currentServerEnvironment SWIFT_WARN_UNUSED_RESULT;
- (BOOL)serverEnvironmentCreated SWIFT_WARN_UNUSED_RESULT;
- (void)selectServerDialog:(UIView * _Nonnull)parentView completionHandler:(void (^ _Nonnull)(enum ServerType))handler;
- (void)statusForOrderIDWithOrderID:(NSString * _Nonnull)orderID responseHandler:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
- (NSString * _Nonnull)domain SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PGTransactionViewController;

SWIFT_PROTOCOL("_TtP10PaymentSDK21PGTransactionDelegate_")
@protocol PGTransactionDelegate
- (void)didFinishedResponse:(PGTransactionViewController * _Nonnull)controller response:(NSString * _Nonnull)responseString;
- (void)didCancelTrasaction:(PGTransactionViewController * _Nonnull)controller;
- (void)errorMisssingParameter:(PGTransactionViewController * _Nonnull)controller error:(NSError * _Nullable)error;
@end

@class WKWebView;
@class NSMutableURLRequest;
@class UIButton;
@class NSBundle;

SWIFT_CLASS("_TtC10PaymentSDK27PGTransactionViewController")
@interface PGTransactionViewController : UIViewController <UIActionSheetDelegate>
@property (nonatomic, strong) PGServerEnvironment * _Nonnull server;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull txnParameters;
@property (nonatomic, copy) NSDictionary * _Nonnull clientAuthServerResponseDict;
@property (nonatomic, strong) WKWebView * _Nullable webView;
@property (nonatomic, strong) NSMutableURLRequest * _Nullable pgRequest;
@property (nonatomic) BOOL isNavigationBarHiddenState;
@property (nonatomic, strong) id <PGTransactionDelegate> _Nullable delegate;
@property (nonatomic) BOOL useStaging;
@property (nonatomic) BOOL isLoggingEnabled;
@property (nonatomic) enum ServerType serverType;
@property (nonatomic, strong) PGMerchantConfiguration * _Nullable merchant;
@property (nonatomic) BOOL sendAllChecksumResponseParamsToPG;
@property (nonatomic, strong) UIView * _Nonnull topBar;
@property (nonatomic, strong) UIButton * _Nonnull cancelButton;
- (nonnull instancetype)initWithTransactionParameters:(NSDictionary<NSString *, id> * _Nonnull)parameters;
- (id _Nonnull)initTransactionFor:(PGOrder * _Nonnull)orderObj SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)loadView;
- (BOOL)isValidRequest SWIFT_WARN_UNUSED_RESULT;
- (void)cancel:(id _Nullable)sender;
- (void)setLoggingEnabled:(BOOL)enabled;
- (void)showProgress:(NSString * _Nonnull)progressString;
- (void)hideProgress;
- (void)didReceiveMemoryWarning;
- (void)finishedResponse:(NSString * _Nonnull)response;
- (void)missingParameter:(NSError * _Nullable)error;
- (void)failedCallback:(NSError * _Nullable)error response:(NSDictionary * _Nonnull)dict;
- (void)successCallback:(NSError * _Nullable)error response:(NSDictionary * _Nonnull)dict;
- (void)cancelCallback;
- (void)beginPGTransaction;
- (void)loadAuthenticatedRequestInWebView;
- (void)pgTransactionEndedWithResponseJSON:(NSString * _Nonnull)json urlEncodedString:(NSString * _Nonnull)urlEncoded;
- (void)cancelCurrentTransaction;
- (void)cleanup;
- (BOOL)isLoadingCallbackURL:(NSString * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (void)validateMerchantChecksum:(NSDictionary * _Nonnull)parms;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKFrameInfo;

@interface PGTransactionViewController (SWIFT_EXTENSION(PaymentSDK)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)runJavaScriptAlertPanelWithMessage initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)runJavaScriptConfirmPanelWithMessage initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)_ runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)runJavaScriptTextInputPanelWithPrompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)initiatedByFrame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
@end

@class WKNavigation;
@class WKNavigationAction;

@interface PGTransactionViewController (SWIFT_EXTENSION(PaymentSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC10PaymentSDK7PGUtils")
@interface PGUtils : NSObject
@property (nonatomic, strong) PGConnectionDelegate * _Null_unspecified delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PGUtils * _Nonnull sharedInstance;)
+ (PGUtils * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogStatus:(BOOL)status;
+ (NSString * _Nonnull)dictionaryToURLEncodedStringWithDict:(NSDictionary * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)dictionaryFromURLEncodedStringWithUrlEncodedString:(NSString * _Nonnull)urlEncodedString SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)dictionaryFromJsonStringWithJsonString:(NSString * _Nonnull)jsonString SWIFT_WARN_UNUSED_RESULT;
+ (OSStatus)extractIdentity:(NSData * _Nonnull)certData SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)noInternetError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)checksumVerificationError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)nilChecksumValidationURL SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nullable)missingParametrs:(NSString * _Nonnull)errorMessage SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)emptyDataError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorForResponseCodeWithResponseCodeStr:(NSString * _Nonnull)responseCodeStr SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorForHTTPCodeWithCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary * _Nonnull)pgResponseCodes SWIFT_WARN_UNUSED_RESULT;
+ (NSURLRequest * _Nonnull)requestForURLWithUrl:(NSString * _Nonnull)url withParms:(NSDictionary * _Nonnull)parms SWIFT_WARN_UNUSED_RESULT;
+ (void)postToURL:(NSString * _Nonnull)url with:(NSString * _Nonnull)value completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
+ (void)postToURL:(NSString * _Nonnull)URL withParms:(NSDictionary * _Nonnull)parms completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
- (void)makeConnectionWith:(NSMutableURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(PGConnectionDelegate * _Nonnull))handler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ServerType, open) {
  ServerTypeEServerTypeProduction = 0,
  ServerTypeEServerTypeStaging = 1,
  ServerTypeEServerTypeNone = 2,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif

#endif
